wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1638453121
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 10
      2:
      - 1
      - 2
      - 3
      - 9
      - 10
      3:
      - 1
      - 13
      - 15
      - 16
      4: 3.7.3
      5: 0.12.7
      8:
      - 5
batch_size:
  desc: null
  value: 100
max_epochs:
  desc: null
  value: 150
